name: 'Read conventional commit CHANGELOG'
description: 'Reads the conventional commit generated CHANGELOG and outputs the requested version changes'
author: Marcos González Andrés
branding:
  icon: 'list'
  color: 'yellow'
inputs:
  changelog-path:
    description: 'The CHANGELOG path. Defaults to ./CHANGELOG.md'
    required: false
    default: './CHANGELOG.md'
  version:
    description: 'The version of the changelog to output. Defaults to latest'
    required: false
    default: latest
outputs:
  version-changelog:
    description: 'The requested version changes'
runs:
  using: 'node12'
  main: 'dist/index.js'
