name: 'Read conventional commit CHANGELOG'
description: "Reads the conventional commit generated CHANGELOG and outputs the requested version changes.\n\n| **package version**          | **github runner version** |\n| :----------------------------- | :------------------------ |\n| < v2.0.0  | < 2.297.0                 |\n| >= v2.0.0 | >= 2.297.0                |"
author: Marcos González Andrés
branding:
  icon: 'list'
  color: 'yellow'
inputs:
  changelog-path:
    description: 'The CHANGELOG path. Defaults to ./CHANGELOG.md'
    required: false
    default: './CHANGELOG.md'
  version:
    description: 'The version of the changelog to output. Defaults to latest'
    required: false
    default: latest
  fail:
    description: 'If false the action will not fail and instead returns empty string if an error is raised. Defaults to true'
    required: false
    default: true
outputs:
  version-changelog:
    description: 'The requested version changes'
runs:
  using: 'node12'
  main: 'dist/index.js'
